package.json

To avoid running into [this bug](visionmedia/debug#356) in the `debug` package.
It would be great to make a new patch release after this has been merge so that downstream packages can depend on at least that version.

:arrow_up: update minimum version of debug dependency

---

index.js
test/test.js

This adds a `defaultPort` field to every instance of the `HttpsProxyAgent` so that Node's internal `https.request` does not add the `:443` port to the `Host` header [here](https://github.com/nodejs/node/blob/master/lib/_http_client.js#L157-L159).
**Note**: This is different from d7a4c70, which only controls the client's request to the Proxy but not the proxied request to the actual server.
**Details:** Node's `ClientRequest` checks the `defaultPort` option and the agent's `defaultPort` and only adds the port to the `Host` header of the actual request if it differs from the `port` option. `agent-base` ensures that this port is always `443` (see [here](https://github.com/TooTallNate/node-agent-base/blob/master/patch-core.js#L20)). Certain applications, such as the AWS/S3 client, even expect …

Add defaultPort field to the HttpsProxyAgent

---

index.d.ts
package.json

This PR is just to bring attention to the missing type definitions. Not everyone uses TypeScript, but for those who do, having this file in this repo would be incredibly helpful.
`index.d.ts` is based on: https://github.com/TooTallNate/node-https-proxy-agent/issues/27#issuecomment-389298156 (thank you @yonilerner)
Please let us know if this is ok! Any form of feedback is appreciated.

TypeScript type definitions

---

index.d.ts

Following up from #66, the constructor can be either the options object or a string (see https://github.com/TooTallNate/node-https-proxy-agent/blob/master/index.js#L27)

feat(typescript): Allow input to be options or string

---

index.d.ts

Fixing a regression spotted in pnpm: https://github.com/pnpm/pnpm/pull/1905
The port in the Node.js URL object is a string, so it is more convenient to use string for the port.
https://nodejs.org/api/url.html#url_url_port

fix(typings): allow port to be a string

---

.travis.yml
test/test.js

This reverts commit 2590f76d6a1a39391ef7dd5046d2132bcd85ff61 as per https://github.com/TooTallNate/node-https-proxy-agent/commit/2590f76d6a1a39391ef7dd5046d2132bcd85ff61#commitcomment-35365193

Revert "Meh…"

---

index.js

This is a fix for https://hackerone.com/reports/541502.
Aborts the upstream proxy connection and instead uses a vanilla `EventEmitter` instance to replay the "data" events on to. This way, the node core `http` Client doesn't attempt to write the HTTP request that is intended to go to the destination server to the proxy server.
Closes #76.
Fixes #78.

Use an `EventEmitter` to replay failed proxy connect HTTP requests

---

.github/workflows/test.yml
index.js
test/test.js

Fixes: https://github.com/TooTallNate/node-https-proxy-agent/issues/81

Use a `net.Socket` instead of a plain `EventEmitter` for replaying proxy errors

---

.github/workflows/test.yml
src/agent.ts

If the socket is writable, a write is attempted and an
`ERR_SOCKET_CLOSED` error is emitted because the socket was never
connected.

Fix compatibility with Node.js 14

---

packages/proxy-agent/package.json
packages/proxy-agent/src/index.ts
pnpm-lock.yaml

ncc v0.24.0 has an issue parsing "lru-cache@9" and also "lru-cache@8" :/
```
ncc: Version 0.24.0
ncc: Compiling file index.js
ncc: Using typescript@4.9.5 (local user-provided)
Error: Module parse failed: Unexpected token (27:15)
File was processed with these loaders:
* ../../node_modules/.pnpm/@vercel+ncc@0.24.0/node_modules/@vercel/ncc/dist/ncc/loaders/empty-loader.js
* ../../node_modules/.pnpm/@vercel+ncc@0.24.0/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js
* ../../node_modules/.pnpm/@vercel+ncc@0.24.0/node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
|     //@ts-ignore
|     AS = class AbortSignal {
>         onabort;
|         _onabort = [];
|         reason;
```

[proxy-agent] Use "lru-cache@7"

---

.changeset/silver-carpets-bow.md
packages/agent-base/package.json
packages/data-uri-to-buffer/package.json
packages/degenerator/package.json
packages/get-uri/package.json
packages/http-proxy-agent/package.json
packages/https-proxy-agent/package.json
packages/pac-proxy-agent/package.json
packages/pac-resolver/package.json
packages/proxy-agent/package.json
packages/proxy/package.json
packages/socks-proxy-agent/package.json
pnpm-lock.yaml

Includes [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65408), so that `http.Agent` properly extends from `EventEmitter`.

Update `@types/node` to v14.18.45

---

.changeset/stupid-queens-listen.md
packages/pac-proxy-agent/src/index.ts

This a recreation of [this PR](https://github.com/TooTallNate/node-pac-proxy-agent/pull/19) from the original repo, with adjustments to match the implementation in other proxy agents.
I had an issue getting an ssl handshake failure error using a PAC based proxy configuration. Turns out `servername` must be provided to tls.connect(). I saw you had had it in your other "...-proxy-agent" so I just added the same here

Add servername to tls options when connecting in DIRECT

---

.changeset/slimy-pillows-do.md
packages/degenerator/src/index.ts

`util.isRegExp()` is marked as deprecated.

[degenerator] Use `util.types.isRegExp()`

---

.changeset/odd-mirrors-nail.md
packages/proxy-agent/src/index.ts
packages/proxy-agent/test/test.ts

This is a recreation of [this PR](https://github.com/TooTallNate/node-proxy-agent/pull/69) from the original repo.
This PR adds the option to provide a getProxyForUrl(url: string) => string function as an option to the ProxyAgent constructor.
We found it useful in places where proxy address is different for different hosts (and pac is not an option).

[proxy-agent] Support for `getProxyForUrl` option

---

.changeset/seven-horses-buy.md
packages/agent-base/src/helpers.ts
packages/agent-base/src/index.ts
packages/agent-base/test/test.ts

During an HTTP request, if `opts.protocol` is set, then use that to determine the `secureEndpoint` value. Coupling that with an explicitly set `agent.protocol` in the instance (essentially "locking" it for use with either `http` or `https` module), then the agent will _never_ rely on the stack trace. By default it will still rely on the stack trace to allow for agent instances to be used with either `http` or `https` modules.
Also moved the internal props to an object using a symbol, instead of relying on underscore props.
Fixes #158.

[agent-base] Allow for never relying on stack trace

---

.changeset/tidy-jobs-refuse.md
packages/https-proxy-agent/src/index.ts
packages/https-proxy-agent/test/test.ts

Currently, the `headers` option can only be passed in when the HttpsProxyAgent is first created, so consumers can only set headers statically.
Typically, proxy headers are used to trace requests as they pass through multiple systems to enable log correlation. If someone wants to reuse a single HttpsProxyAgent for multiple requests, this isn't ideal.
This PR updates the `headers` option so that it can also be a function that returns an object, allowing consumers to set the proxy headers dynamically.
Companion PR to update HttpProxyAgent: #175

Support dynamic headers for `https-proxy-agent`

---

.changeset/shiny-badgers-obey.md
packages/proxy/src/proxy.ts

It's possible that this value is `undefined`, so skip adding it to the `x-forwarded-for` header in that case.

[proxy] Ensure that `socket.remoteAddress` is a string

---

.changeset/unlucky-cows-listen.md
packages/http-proxy-agent/README.md
packages/http-proxy-agent/src/index.ts
packages/http-proxy-agent/test/test.ts

Currently, HttpProxyAgent does not have a `headers` option at all. The HttpsProxyAgent does, though.
This PR adds a `headers` option, allowing consumers to set the proxy headers statically or dynamically.
Companion PR to update HttpsProxyAgent: #174

Support headers for `http-proxy-agent`

---

.changeset/eleven-seas-rule.md
packages/https-proxy-agent/package.json
packages/https-proxy-agent/src/parse-proxy-response.ts
packages/https-proxy-agent/test/test.ts
pnpm-lock.yaml

[https-proxy-agent] Properly reject errors during proxy CONNECT response

---

.changeset/gentle-panthers-stare.md
packages/https-proxy-agent/src/parse-proxy-response.ts
packages/proxy/src/proxy.ts

I have not done heavy testing, but has not broken yet.  Hopefully meets the need.

[https-proxy-agent] Slice the headers when parsing proxy server response

---

.changeset/flat-cherries-watch.md
packages/degenerator/package.json
pnpm-lock.yaml

This removes `optionator` which further down the line also removes `word-wrap` v1.2.3 which has a security vulnerability. The breaking change occuring for `escodegen` v2 is that it requires Node 6 now instead of Node 4 which is not an issue for this project.
It seems that there are a few changes to the pnpm lockfile that look like they might not be related to this PR but I have installed version 7.32.2 (as mentioned in the test CI workflow), installed dependencies before changing anything and all these changes seem to be coming from that.

[degenerator] Update escodegen

---

.changeset/four-teachers-peel.md
packages/https-proxy-agent/src/index.ts

https://github.com/TooTallNate/proxy-agents/issues/14 adds a full SNI support for target servers but not proxy servers. TLS connection to proxy servers also needs SNI setting or it will raise a `Hostname/IP deosn't match` certificate error. And I think `servername` should be the proxy server host by default even the `HttpsProxyAgent` constructor can take `servername` property.

[https-proxy-agent] Support SNI as default for proxy servers

---

.changeset/eleven-bags-attend.md
packages/pac-proxy-agent/src/index.ts
packages/proxy-agent/src/index.ts
packages/socks-proxy-agent/src/index.ts

`new URL('socks://host:port')` gives different results in browser and Node.js because `socks` is not among the "special schemes" specified by WHATWG and thus the hostname is treated as an opaque value (without parsing the port). Node.js implementation, however, parses the `port`.
Since `proxy-agent` can be used in Electron, unless `URL` is imported directly from the Node's `url` module - it is going to use the Browser's version of it which won't work with socks urls.

Use non-compliant URL from 'url' for socks urls

---

.changeset/lucky-items-lay.md
packages/data-uri-to-buffer/README.md
packages/data-uri-to-buffer/package.json
packages/data-uri-to-buffer/src/index.ts
packages/data-uri-to-buffer/test/data-uri-to-buffer.test.ts
packages/get-uri/src/data.ts

Refactor to return an `ArrayBuffer` instead of a Node.js `Buffer`.
This change is being made to make the package platform-agnostic, and work in web browsers or other non-Node.js environments without polyfills.
For Node.js users of this package, you can get a Node.js `Buffer` instance from an `ArrayBuffer` like so:
```typescript
const uri = 'data:,Hello%2C%20World!';
const parsed = dataUriToBuffer(uri);
const buffer = Buffer.from(parsed.buffer);
// `buffer` is a Node.js Buffer
```

[data-uri-to-buffer] Refactor to return an `ArrayBuffer` instead of a Node.js `Buffer`

---

.changeset/neat-rules-brake.md
packages/http-proxy-agent/src/index.ts
packages/https-proxy-agent/src/index.ts

Fix: "URL" types were missing for below packages:
+ http-proxy-agent
+ https-proxy-agent
*Error fixed:*

fix: URL types were missing

---

.changeset/few-adults-rhyme.md
packages/data-uri-to-buffer/package.json
packages/data-uri-to-buffer/src/common.ts
packages/data-uri-to-buffer/src/index.ts
packages/data-uri-to-buffer/src/node.ts
packages/data-uri-to-buffer/test/data-uri-to-buffer.test.ts

I saw in https://github.com/microsoft/vscode-js-debug/issues/1911 that
base64 decoding of a data URI was taking a bit of time.
This PR feature-detects the presence of a global `Buffer` to use native
decoding when running in Node.js, which is about 25x faster on a 10MB
data URI than the JS implementation in the library.
I have a bit of a hack in order to test both paths when running tests,
happy to change it if desired :)

Make decoding of base64 data URIs faster

---

.changeset/nice-pillows-type.md
packages/proxy-agent/src/index.ts
packages/proxy-agent/test/test.ts

This allows users to use an asynchronous `getProxyForUrl` in case they need to do asynchronous operations to resolve the correct proxy URL.  This can be the case, for example, if using `Electron.Session.resolveProxy(url)`.
Fixes #264
Test suites seem to pass; added a new one to exercise this functionality, but I can delete it if that seems like overkill.
I opted for a patch level release, because this should not affect any existing users.

[proxy-agent] Allow asynchronous `getProxyForUrl`

---

.changeset/heavy-planets-stare.md
packages/pac-resolver/package.json
packages/pac-resolver/src/ip.ts
packages/pac-resolver/src/myIpAddress.ts
pnpm-lock.yaml

There is a `high` severity [vulnerability](https://github.com/advisories/GHSA-78xj-cgh5-2h22) in the https://github.com/indutny/node-ip package
Unfortunately this package was updated long time ago and seems to be dead
This PR aims to fix the aforementioned issue by getting rid of the `node-ip` dependency in favour of using copied [parts of code](https://github.com/indutny/node-ip/blob/main/lib/ip.js) which are used in this lib
Fixes: https://github.com/TooTallNate/proxy-agents/issues/280

[pac-resolver] Remove `ip` dependency

---

.github/workflows/release.yml
.github/workflows/test.yml

The following updates are performed:
* update [`actions/checkout`](https://github.com/actions/checkout) to v4
* update [`actions/setup-node`](https://github.com/actions/setup-node) to v4
* update [`pnpm/action-setup`](https://github.com/pnpm/action-setup) to v3
Still using the outdated actions will generate several warnings in CI runs, for example in https://github.com/TooTallNate/proxy-agents/actions/runs/7876212832:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, pnpm/action-setup@v2, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
The PR will get rid of those warnings.

chore: update actions in GitHub Actions workflows

---

.changeset/strong-cups-listen.md
packages/http-proxy-agent/src/index.ts
packages/https-proxy-agent/src/index.ts

The following PR introduced a regression in Node 14, as that version of node doesn't support `node:url`.
- https://github.com/TooTallNate/proxy-agents/pull/268
Original issue:
- https://github.com/googleapis/nodejs-storage/issues/2403

fix: `URL` imports for Node 14

---

.changeset/seven-colts-flash.md
packages/agent-base/src/index.ts
packages/agent-base/test/test.ts

Fixes #299
This is a bit of a hack, but I went with this approach because it allows for all of the native socket pooling behavior in `http.Agent` to be used and `connect()` to keep it's async signature.
The tradeoff is manipulating the internal `sockets` dictionary which is `readonly` (according to `@types/node`) and therefore needs a lot of `@ts-expect-error` comments. An alternative approach would require overwriting the `addRequest()` method with custom pooling code.
The approach in this PR works by synchronously adding a fake socket to the pool so `this.sockets[originName].length` is accurate before any other requests are added. Then the socket is removed directly after `connect()` finishes.

Synchronously update internal sockets length so http.Agent pooling is used

---

.changeset/silver-pumas-drum.md
packages/socks-proxy-agent/src/index.ts
packages/socks-proxy-agent/test/test.ts

This PR adds the option `socketOptions` which will get passed along to `SocksClient.createConnection` as `socket_options`.
Another solution would be to spread all the unused constructor options to the `SocksClient.createConnection` options since there are a few more that are allowed. I didn't go this route since I only have a use case for `socket_options` and I didn't want to couple the two APIs too closely. But I'd be happy to rework this PR if desired.
For reference the [`SocksClientOptions` interface](https://github.com/JoshGlazebrook/socks/blob/76d013e4c9a2d956f07868477d8f12ec0b96edfc/typings/common/constants.d.ts#L123-L131) is:
```ts
interface SocksClientOptions {
command: SocksCommandOption;
destination: SocksRemoteHost;
proxy: SocksProxy;
timeout?: number;
existing_socket?: Duplex; …
```

[socks-proxy-agent] pass socket_options to SocksClient

---

.changeset/dirty-eagles-jog.md
packages/get-uri/package.json
packages/get-uri/src/file.ts
packages/get-uri/test/file.test.ts
packages/get-uri/test/ftp.test.ts
packages/get-uri/test/http.test.ts
packages/get-uri/test/https.test.ts
packages/get-uri/test/redirect.test.ts
pnpm-lock.yaml

Since the `get-uri` package requires Node.js 14 or higher, the `fs-extra` package can be removed and its features replaced with native Node.js functionality.

[get-uri] Remove `fs-extra` dependency

---

.changeset/unlucky-vans-shout.md
packages/proxy-agent/package.json
packages/proxy-agent/src/index.ts
pnpm-lock.yaml

Destroy agent instances when disposed from cache

---

.changeset/late-berries-rule.md
packages/proxy-agent/src/index.ts

Some of the references packages can be quite expensive to instantiate (e.g. pac-proxy-agent and its custom JS runtime), so lazily loading them enables fast loading times for the more common cases.

[proxy-agent] Lazily load agents

---

.changeset/sixty-carpets-cross.md
packages/proxy-agent/src/index.ts
packages/proxy-agent/test/test.ts

Same as #326 with one minor change in 869ecbc36cdb363bae4b5cbae66cf68c09fe3488 to keep the optionality of the constructor and getProxyForUrl arguments to keep TypeScript happy.
Closes #326.

Pass req to getProxyForUrl callback

---

.changeset/pretty-terms-exercise.md
packages/agent-base/src/index.ts

`tls.createSecureContext()` can throw exceptions, so `.addRequest()` can throw exceptions as well.

Handle exceptions from agent addRequest()

---

.changeset/lovely-boxes-heal.md
packages/https-proxy-agent/src/index.ts
packages/pac-proxy-agent/src/index.ts
packages/socks-proxy-agent/src/index.ts

This is an alternative to #337 (which was created to revert #312).
Based on the original report in #308, I think reverting is not ideal since it would (re-)break the use case described where Kubernetes issues certificates for hosts that area reachable by IP. (Kubernetes is not an area I have much experience in so this is reiterating the original report but I have not tested this.)
But I do think the end result of #337 is nice in that it removes the warning for a common use case. Regardless of Node showing a deprecation warning and RFC 6066, it would be nice not to show the warning since even the tests in this repo trigger the deprecation message.
I searched a bit and found an example of `node-postres` handling this same issue with a solution that accounts for both situations: …

Only overwrite servername in tls connect when host is not an IP address

---

.changeset/bright-rocks-dance.md
packages/pac-proxy-agent/src/index.ts

Ref: https://github.com/TooTallNate/proxy-agents/pull/327#issuecomment-2519218645
This has less of an effect than #327 since `pac-proxy-agent` is the biggest one. But I think it makes sense for consistency and because a common use case or `pac-proxy-agent` is with `DIRECT` which would never load the other proxies.

lazy load non-direct proxies within pac-proxy

---

.changeset/popular-toys-happen.md
packages/pac-proxy-agent/src/index.ts
packages/pac-proxy-agent/test/test.ts

This enables calling code to determine the proxy that will be used for a remote host without actually initiating a connection to it.
Fixes #362

[pac-proxy-agent] Expose `PacProxyAgent.getResolver()` publicly

---

.changeset/short-spiders-travel.md
packages/agent-base/src/index.ts

In `@types/node@20.19.2`, `getName` was added (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/239534ac5225c56966e7df1b83aeba21a29f6349) with an optional argument, meaning `Agent` is not assignable to the `@types/node` declaration. This makes the `options` object optional and removes the unnecessary `options.secureEndpoint` check since `this.isSecureEndpoint` already handles it.
From history of [`Agent.prototype.getName` in Node documentation](https://nodejs.org/api/http.html#agentgetnameoptions):
> v17.7.0, v16.15.0 | The options parameter is now optional.
Based on that line, I think the `@types/node` interpretation is accurate and this `Agent` implementation should assume the parameter may not be provided.
I do see several explicit `any` and `@ts-expect-error` related to the …

Make options for `Agent.prototype.getName` optional
